import '../styling/App.css'
export default function GMBaudit() {
    return (
        <>
        <div className='gmb-box'>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <div className='single-line'>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
                <div className='gmb-square'></div>
            </div>
            <SquareAudit/>
        </div>
        </>
    )
}

function SquareAudit() {
    return (
        <div className='square-audit'>
            <h2>and audit gmb</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis animi corporis totam pariatur, laborum, fugit sit similique tenetur, iusto ratione deserunt dolorem? Quae commodi culpa reiciendis inventore iure. Iure, in!</p>
            <button>sign up</button>
        </div>
    )
}